# Generated by Django 4.2.7 on 2023-11-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=55, null=True, verbose_name='pol')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='soname')),
                ('street_number', models.IntegerField(blank=True, null=True, verbose_name='номкр дома')),
                ('street_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город проживания')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна проживания')),
                ('postcode', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='почтовый индекс')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='никнейм')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='пароль пользователя')),
                ('born_data', models.CharField(blank=True, max_length=55, null=True, verbose_name='дата рождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='возраст')),
            ],
        ),
    ]
